name: Website
on:
  push:
    branches:
    - main

permissions: read-all

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
      with:
        persist-credentials: false
    - name: Build
      run: make deploy-web
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@ec9c88baef04b842ca6f0a132fd61c762aa6c1b0 # v4.6.0
      with:
        branch: gh-pages
        folder: _site
        single-commit: true
